apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: gowiki-demo
spec:
  containers:
  - name: myapp-container
    image: hanksudo/gowiki-demo:1.0.0
    ports:
    - containerPort: 8000